import db from '../config/db.js';

export const createImpersonationCode = async ({ code, ngo_id, created_by, created_by_name, expires_at }) => {
  const { data, error } = await db
    .from('impersonation_codes')
    .insert([{ code, ngo_id, created_by, created_by_name, expires_at }])
    .select()
    .single();
  if (error) throw error;
  return data;
};

// Find a code that is still valid for the given NGO. Codes are ngo-scoped:
// ngo_id must match (or be null for global codes generated by a super admin).
export const findValidImpersonationCode = async (code, ngoId) => {
  let query = db
    .from('impersonation_codes')
    .select('*')
    .eq('code', code)
    .eq('is_used', false)
    .gt('expires_at', new Date().toISOString());
  if (ngoId != null) {
    query = query.or(`ngo_id.eq.${ngoId},ngo_id.is.null`);
  }
  query = query.limit(1);
  const { data, error } = await query;
  if (error) throw error;
  return (data || [])[0] || null;
};

export const markImpersonationCodeUsed = async (id, usedBy) => {
  const { data, error } = await db
    .from('impersonation_codes')
    .update({ is_used: true, used_at: new Date().toISOString(), used_by: usedBy })
    .eq('id', id)
    .eq('is_used', false)
    .select()
    .single();
  if (error && error.code !== 'PGRST116') throw error;
  return data;
};

export const listImpersonationCodes = async (ngoId, limit = 50) => {
  const now = new Date().toISOString();
  const cutoff = new Date(Date.now() - 30 * 60 * 1000).toISOString();

  // Show active codes (not used & not expired) OR any code created in the last
  // 30 minutes.  When ngoId is supplied, scope both branches to that NGO.
  // PostgREST .or() syntax: top-level comma = OR, and() = AND.
  let filter;
  if (ngoId != null) {
    const ngo = `or(ngo_id.eq.${ngoId},ngo_id.is.null)`;
    filter = `and(is_used.eq.false,expires_at.gt.${now},${ngo}),and(created_at.gt.${cutoff},${ngo})`;
  } else {
    filter = `and(is_used.eq.false,expires_at.gt.${now}),created_at.gt.${cutoff}`;
  }

  const { data, error } = await db
    .from('impersonation_codes')
    .select('*')
    .or(filter)
    .order('created_at', { ascending: false })
    .limit(limit);
  if (error) throw error;
  return data || [];
};

export const listAllImpersonationCodes = async () => {
  const { data, error } = await db
    .from('impersonation_codes')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return data || [];
};
