-- ---------------------------------------------------------------------------
-- Sevak Library schema for the UCS CRM main Postgres (AWS RDS).
--
-- Recreated from supabase/migrations/* of the SevakLibrary project by removing
-- Supabase-specific concerns: no RLS, no auth.users dependency, no plpgsql RPCs
-- (that logic now lives in backend/src/sevakLibrary as JS).
--
-- Idempotent. Run via:  psql "$DATABASE_URL" -f scripts/sevak-library-schema.sql
-- or from migrate-sevak-library.mjs.
-- ---------------------------------------------------------------------------

create table if not exists public.applications (
  id                  bigint generated by default as identity primary key,
  ref                 text unique not null,
  payment_ref         text,
  data                jsonb not null default '{}'::jsonb,
  passport_photo      text,
  identity_photo      text,
  full_name           text,
  email               text,
  mobile              text,
  membership_type     text,
  membership_fee      numeric,
  start_date          date,
  end_date            date,
  identity_proof_type text,
  identity_number     text,
  status              text not null default 'SUBMITTED',
  transaction_id      text,
  membership_id       text,
  reject_reason       text,
  renewal_email_sent  boolean not null default false,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists idx_applications_status on public.applications(status);
create index if not exists idx_applications_ref   on public.applications(ref);
create index if not exists idx_applications_email on public.applications(email);
create index if not exists idx_applications_mobile on public.applications(mobile);

create table if not exists public.coupons (
  id             bigint generated by default as identity primary key,
  code           text unique not null,
  description    text,
  discount_type  text not null default 'percent' check (discount_type in ('percent', 'flat')),
  discount_value numeric not null check (discount_value > 0),
  min_fee        numeric,
  valid_from     date,
  valid_until    date,
  max_uses       int check (max_uses is null or max_uses >= 0),
  uses_count     int not null default 0,
  active         boolean not null default true,
  created_at     timestamptz not null default now()
);

create table if not exists public.mail_log (
  id             bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete set null,
  to_email       text,
  subject        text,
  body           text,
  membership_id  text,
  sent           boolean not null default false,
  error          text,
  created_at     timestamptz not null default now()
);