ALTER TABLE receipts ADD COLUMN IF NOT EXISTS caller_name TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS mobile_2 TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS address_2 TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS station TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS account_of TEXT;
