-- 098: batch identifier for station_rename_log rows.
--
-- Every applied bulk-rename batch now stamps its audit rows with a shared
-- batch_id (generated by the handler), so the revert UI can group and reverse
-- a whole run in one click. The handler also runs this DDL (IF NOT EXISTS) on
-- first use, so existing installs (e.g. production, where the table was
-- auto-created by the handler) get the column automatically.

ALTER TABLE station_rename_log ADD COLUMN IF NOT EXISTS batch_id uuid;

CREATE INDEX IF NOT EXISTS idx_station_rename_log_batch
  ON station_rename_log(batch_id);
