-- 098: batch identifier for station_rename_log rows.
--
-- Every applied bulk-rename batch now stamps its audit rows with a shared
-- batch_id (generated by the handler), so the revert UI can group and reverse
-- a whole run in one click. The handler also runs this DDL (IF NOT EXISTS) on
-- first use, so existing installs (e.g. production, where the table was
-- auto-created by the handler) get the column automatically.
--
-- Self-sufficient: if migration 097 was never applied on this database, the
-- table is created here complete (including batch_id). Everything is
-- IF NOT EXISTS, so this file is safe to run on any database in any state
-- and in any order relative to 097.

CREATE TABLE IF NOT EXISTS station_rename_log (
  id             bigserial PRIMARY KEY,
  ngo_id         uuid,
  ngo_name       text,
  old_station    text NOT NULL,
  new_station    text NOT NULL,
  counts         jsonb NOT NULL DEFAULT '{}',
  skipped_donors integer NOT NULL DEFAULT 0,
  performed_by   text,
  performed_at   timestamptz NOT NULL DEFAULT now(),
  batch_id       uuid
);

ALTER TABLE station_rename_log ADD COLUMN IF NOT EXISTS batch_id uuid;

CREATE INDEX IF NOT EXISTS idx_station_rename_log_ngo_time
  ON station_rename_log(ngo_id, performed_at DESC);

CREATE INDEX IF NOT EXISTS idx_station_rename_log_old_station
  ON station_rename_log(old_station);

CREATE INDEX IF NOT EXISTS idx_station_rename_log_batch
  ON station_rename_log(batch_id);
