import {
  Bell,
  Box,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleUser,
  Copy,
  Database,
  DatabaseX,
  Gauge,
  HelpCircle,
  KeyRound,
  Loader2,
  Plus,
  Rows3,
  Search,
  Settings,
  Table2,
  Terminal,
  Trash2,
  UserPlus,
  X,
} from 'lucide-react';

const map = {
  database: Database,
  add: Plus,
  table_chart: Table2,
  terminal: Terminal,
  speed: Gauge,
  table_rows: Rows3,
  settings: Settings,
  help: HelpCircle,
  notifications: Bell,
  account_circle: CircleUser,
  search: Search,
  arrow_drop_down: ChevronDown,
  close: X,
  delete: Trash2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  arrow_drop_up: ChevronUp,
  unfold_more: ChevronsUpDown,
  database_off: DatabaseX,
  user_plus: UserPlus,
  copy: Copy,
  key: KeyRound,
  check: CheckCircle2,
  bucket: Box,
  loader: Loader2,
};

export default function Icon({ name, className = '', size = 20 }) {
  const Cmp = map[name] || Database;
  return <Cmp className={className} size={size} strokeWidth={2} />;
}
