// ─────────────────────────────────────────────────────────────────────────────
// Curated reference calendar for the Event Head planner (Worldwide + India).
//
// RELIABILITY CONTRACT — read this before editing:
//  • Every date below is either a FIXED month/day rule (identical every year) or
//    an explicit per-year date recorded for a named festival.
//  • NOTHING in this file is generated by an AI model. Gemini is only ever asked
//    for *activity ideas* (see suggestDayPrograms in eventHeadController.js).
//    The model never returns, corrects, or invents a date for this calendar.
//  • `precision: 'lunar'` entries follow the Indian lunar calendar / moon sighting
//    and can differ by a day between the gazette notification and local observance.
//    They are flagged in the UI so a coordinator confirms before planning.
//  • If a year has no row for a lunar festival, that festival is simply OMITTED
//    for that year rather than guessed.
//  • Rows in the `holidays` table (added through /api/holidays) are merged on top
//    by mergeCustomObservances() and override a curated row with the same date +
//    name, so a correction never needs a redeploy.
//
// Entry shape:
//   { m, d, name, scope, kind, themes[], precision?, note? }        — fixed rule
//   { date: 'YYYY-MM-DD', name, scope, kind, themes[], … }         — per-year row
//
// scope : 'worldwide' | 'india'
// kind  : 'observance' | 'national' | 'festival' | 'religious' | 'week'
// themes: slugs used to ground Gemini suggestions in the org's 12 sectors.
// ─────────────────────────────────────────────────────────────────────────────

const W = 'worldwide';
const I = 'india';

/* ── Fixed month/day rules — the same day every year ───────────────────────── */
// Kept deliberately curated: only observances an Indian NGO can realistically
// build a programme around. Themed to the event_head_sectors list.
const FIXED = [
  /* January */
  { m: 1, d: 2,  name: 'World Braille Day',            scope: W, kind: 'observance', themes: ['education', 'disability'], note: 'Raises awareness of braille and the needs of blind and visually impaired people.' },
  { m: 1, d: 5,  name: 'National Bird Day (India)',    scope: I, kind: 'observance', themes: ['environment'], note: 'India — celebrates the Indian Roller, the national bird.' },
  // NOTE: Makar Sankranti is intentionally absent here. It follows the solar
  // month transition, so it drifts year to year and is tabulated per-year in
  // BY_YEAR below. A fixed Jan-14 rule produced a duplicate chip in every year.
  { m: 1, d: 15, name: 'Army Day (India)',            scope: I, kind: 'national',   themes: ['rights', 'community'] },
  { m: 1, d: 23, name: 'Netaji Subhas Chandra Bose Jayanti', scope: I, kind: 'national', themes: ['rights', 'community'] },
  { m: 1, d: 24, name: 'International Day of Education', scope: W, kind: 'observance', themes: ['education'], note: 'UN-designated day for education.' },
  { m: 1, d: 26, name: 'Republic Day (India)',         scope: I, kind: 'national',   themes: ['rights', 'community'], note: 'Constitution Day — national civic holiday.' },
  { m: 1, d: 27, name: 'International Holocaust Remembrance Day', scope: W, kind: 'observance', themes: ['rights', 'education'] },

  /* February */
  { m: 2, d: 4,  name: 'World Cancer Day',             scope: W, kind: 'observance', themes: ['health'], note: 'Global awareness day for cancer prevention and care.' },
  { m: 2, d: 6,  name: 'International Day against Female Genital Cutting', scope: W, kind: 'observance', themes: ['rights', 'women-children', 'health'] },
  { m: 2, d: 11, name: 'International Day of Women and Girls in Science', scope: W, kind: 'observance', themes: ['women-children', 'education', 'technology'] },
  { m: 2, d: 13, name: 'World Radio Day',              scope: W, kind: 'observance', themes: ['education', 'community'] },
  { m: 2, d: 20, name: 'World Day of Social Justice',  scope: W, kind: 'observance', themes: ['rights', 'social-inclusion'] },
  { m: 2, d: 21, name: 'International Mother Language Day', scope: W, kind: 'observance', themes: ['education'], note: 'Promotes linguistic and cultural diversity.' },
  { m: 2, d: 28, name: 'National Science Day (India)', scope: I, kind: 'observance', themes: ['education', 'technology'], note: 'Marks C. V. Raman — popular for school science exhibitions.' },

  /* March */
  { m: 3, d: 3,  name: 'World Wildlife Day',           scope: W, kind: 'observance', themes: ['environment'] },
  { m: 3, d: 8,  name: 'International Women\'s Day',   scope: W, kind: 'observance', themes: ['women-children', 'rights'], note: 'One of the highest-impact campaign days of the year for women-focused NGOs.' },
  { m: 3, d: 9,  name: 'National Youth Day (India)',   scope: I, kind: 'national',   themes: ['education', 'livelihoods'], note: 'Marks the birth of Swami Vivekananda.' },
  { m: 3, d: 14, name: 'International Day of Mathematics (Pi Day)', scope: W, kind: 'observance', themes: ['education'] },
  { m: 3, d: 20, name: 'World Oral Health Day',        scope: W, kind: 'observance', themes: ['health'], note: 'Strong fit for dental check-up camps.' },
  { m: 3, d: 21, name: 'International Day of Forests', scope: W, kind: 'observance', themes: ['environment'] },
  { m: 3, d: 21, name: 'World Down Syndrome Day',       scope: W, kind: 'observance', themes: ['disability', 'health', 'education'] },
  { m: 3, d: 21, name: 'World Poetry Day',             scope: W, kind: 'observance', themes: ['education', 'sports-culture'] },
  { m: 3, d: 22, name: 'World Water Day',              scope: W, kind: 'observance', themes: ['environment', 'health'] },
  { m: 3, d: 23, name: 'World Meteorological Day',      scope: W, kind: 'observance', themes: ['environment'] },
  { m: 3, d: 24, name: 'World Tuberculosis Day',       scope: W, kind: 'observance', themes: ['health'], note: 'Well established date for TB screening drives.' },

  /* April */
  { m: 4, d: 2,  name: 'World Autism Awareness Day',   scope: W, kind: 'observance', themes: ['disability', 'education', 'health'] },
  { m: 4, d: 7,  name: 'World Health Day',             scope: W, kind: 'observance', themes: ['health'], note: 'WHO founding day — the single largest global health campaign date.' },
  { m: 4, d: 14, name: 'World Parkinson\'s Day',       scope: W, kind: 'observance', themes: ['health'] },
  { m: 4, d: 14, name: 'Dr. B. R. Ambedkar Jayanti (India)', scope: I, kind: 'national', themes: ['rights', 'disability', 'education'], note: 'Fits accessibility, equal-opportunity and anti-discrimination drives.' },
  { m: 4, d: 21, name: 'World Creativity and Innovation Day', scope: W, kind: 'observance', themes: ['livelihoods', 'education', 'technology'] },
  { m: 4, d: 22, name: 'Earth Day',                    scope: W, kind: 'observance', themes: ['environment'], note: 'Largest global environmental campaign day.' },
  { m: 4, d: 23, name: 'World Book Day / International Day of the Book', scope: W, kind: 'observance', themes: ['education'] },
  { m: 4, d: 25, name: 'World Malaria Day',            scope: W, kind: 'observance', themes: ['health'] },
  { m: 4, d: 28, name: 'World Day for Safety and Health at Work', scope: W, kind: 'observance', themes: ['health', 'livelihoods', 'rights'] },

  /* May */
  { m: 5, d: 1,  name: 'International Workers\' Day / Labour Day', scope: W, kind: 'observance', themes: ['livelihoods', 'rights'], note: 'Key date for skilling, artisan and worker-welfare programmes.' },
  { m: 5, d: 3,  name: 'World Press Freedom Day',      scope: W, kind: 'observance', themes: ['rights', 'education'] },
  { m: 5, d: 8,  name: 'World Red Cross and Red Crescent Day', scope: W, kind: 'observance', themes: ['health', 'social-inclusion'] },
  { m: 5, d: 12, name: 'International Nurses Day',      scope: W, kind: 'observance', themes: ['health'], note: 'Fits tribute events and community health camps.' },
  { m: 5, d: 15, name: 'International Day of Families',scope: W, kind: 'observance', themes: ['social-inclusion', 'women-children'] },
  { m: 5, d: 17, name: 'World Speech and Communication Day', scope: W, kind: 'observance', themes: ['disability', 'health', 'education'], note: 'Designed for speech-therapy and AAC awareness programmes.' },
  { m: 5, d: 19, name: 'World Bee Day',                scope: W, kind: 'observance', themes: ['environment', 'livelihoods'], note: 'Strong fit for beekeeping / honey livelihood training.' },
  { m: 5, d: 21, name: 'International Day for Biological Diversity', scope: W, kind: 'observance', themes: ['environment'] },
  { m: 5, d: 21, name: 'International Tea Day',        scope: W, kind: 'observance', themes: ['nutrition', 'livelihoods'] },
  { m: 5, d: 28, name: "International Day of Action for Women's Health", scope: W, kind: 'observance', themes: ['women-children', 'health'] },
  { m: 5, d: 31, name: 'World No Tobacco Day',         scope: W, kind: 'observance', themes: ['health'], note: 'Widely used for tobacco-free / anti-smoking drives.' },

  /* June */
  { m: 6, d: 3,  name: 'World Bicycle Day',            scope: W, kind: 'observance', themes: ['environment', 'health', 'disability'] },
  { m: 6, d: 5,  name: 'World Environment Day',        scope: W, kind: 'observance', themes: ['environment'], note: 'UN flagship day for climate, waste and habitat action.' },
  { m: 6, d: 6,  name: 'World Blood Donor Day',        scope: W, kind: 'observance', themes: ['health'], note: 'Built for voluntary blood donation camps.' },
  { m: 6, d: 7,  name: 'World Food Safety Day',        scope: W, kind: 'observance', themes: ['nutrition', 'health'] },
  { m: 6, d: 8,  name: 'World Oceans Day',             scope: W, kind: 'observance', themes: ['environment'] },
  { m: 6, d: 10, name: 'International Mine Awareness Day', scope: W, kind: 'observance', themes: ['rights', 'social-inclusion'] },
  { m: 6, d: 12, name: 'World Day Against Child Labour', scope: W, kind: 'observance', themes: ['rights', 'education', 'children'] },
  { m: 6, d: 14, name: 'World Elder Abuse Awareness Day', scope: W, kind: 'observance', themes: ['social-inclusion', 'health', 'rights'] },
  { m: 6, d: 15, name: 'International Yoga Day',      scope: W, kind: 'observance', themes: ['health', 'sports-culture'], note: 'Well suited to therapy, wellness and rehabilitation sessions.' },
  { m: 6, d: 16, name: 'International Day for the Elimination of Sexual Violence in Conflict', scope: W, kind: 'observance', themes: ['rights', 'women-children'] },
  { m: 6, d: 20, name: 'World Refugee Day',            scope: W, kind: 'observance', themes: ['social-inclusion', 'livelihoods'] },
  { m: 6, d: 22, name: 'International Day of the Tropics', scope: W, kind: 'observance', themes: ['environment'] },
  { m: 6, d: 23, name: 'International Day of Women in Public Service', scope: W, kind: 'observance', themes: ['women-children', 'rights'] },
  { m: 6, d: 26, name: 'International Day against Drug Abuse and Illicit Trafficking', scope: W, kind: 'observance', themes: ['health', 'rights'] },
  { m: 6, d: 30, name: 'National Milk Day (India)',    scope: I, kind: 'observance', themes: ['nutrition', 'livelihoods'], note: 'India — dairy and nutrition awareness.' },

  /* July */
  { m: 7, d: 1,  name: 'National Doctor\'s Day (India)', scope: I, kind: 'observance', themes: ['health'], note: 'India — honours Dr. B. C. Roy.' },
  { m: 7, d: 2,  name: 'International Day of Cooperatives', scope: W, kind: 'observance', themes: ['livelihoods'], note: 'Fits SHG / cooperative promotion work.' },
  { m: 7, d: 5,  name: 'World Zoonoses Day',           scope: W, kind: 'observance', themes: ['health', 'environment'] },
  { m: 7, d: 11, name: 'World Population Day',         scope: W, kind: 'observance', themes: ['health', 'social-inclusion'] },
  { m: 7, d: 15, name: 'World Justice Day',            scope: W, kind: 'observance', themes: ['rights'] },
  { m: 7, d: 18, name: 'Nelson Mandela International Day', scope: W, kind: 'observance', themes: ['rights', 'social-inclusion', 'education'] },
  { m: 7, d: 20, name: 'International Moon Day',       scope: W, kind: 'observance', themes: ['environment'] },
  { m: 7, d: 22, name: 'World Brain Day',               scope: W, kind: 'observance', themes: ['health', 'disability'] },
  { m: 7, d: 26, name: 'International Day for the Prevention of Torture', scope: W, kind: 'observance', themes: ['rights'] },
  { m: 7, d: 28, name: 'World Hepatitis Day',          scope: W, kind: 'observance', themes: ['health'] },

  /* August */
  { m: 8, d: 1,  name: 'World Chronic Obstructive Pulmonary Disease Day', scope: W, kind: 'observance', themes: ['health'] },
  { m: 8, d: 9,  name: 'International Day of the World\'s Indigenous Peoples', scope: W, kind: 'observance', themes: ['rights', 'social-inclusion'] },
  { m: 8, d: 12, name: 'International Youth Day',      scope: W, kind: 'observance', themes: ['education', 'livelihoods'] },
  { m: 8, d: 15, name: 'Independence Day (India)',     scope: I, kind: 'national',   themes: ['rights', 'community'], note: 'National holiday — flag-hoisting, pledge and civic activity dates.' },
  { m: 8, d: 19, name: 'International Day for the Remembrance of the International Slave Trade', scope: W, kind: 'observance', themes: ['rights', 'education'] },
  { m: 8, d: 21, name: 'International Day for the Commemoration of the International Slave Trade', scope: W, kind: 'observance', themes: ['rights', 'education'] },
  { m: 8, d: 30, name: 'National Women\'s Day (India)', scope: I, kind: 'observance', themes: ['women-children', 'rights', 'livelihoods'] },

  /* September */
  { m: 9, d: 5,  name: 'International Day of Charity', scope: W, kind: 'observance', themes: ['social-inclusion', 'rights'], note: 'UN day dedicated to charitable giving and service.' },
  { m: 9, d: 5,  name: "Teachers' Day (India)",        scope: I, kind: 'observance', themes: ['education'], note: 'India — Guru Dakshin Gyan Divas, marks the birth of Dr. Radhakrishnan.' },
  { m: 9, d: 7,  name: 'International Day of Clean Air', scope: W, kind: 'observance', themes: ['environment', 'health'] },
  { m: 9, d: 8,  name: 'International Literacy Day',    scope: W, kind: 'observance', themes: ['education'], note: 'Fits adult literacy and learning-enrolment drives.' },
  { m: 9, d: 10, name: 'World Suicide Prevention Day',  scope: W, kind: 'observance', themes: ['health', 'rights'], note: 'Mental-health awareness and helpline outreach.' },
  { m: 9, d: 14, name: 'Hindi Day (India)',            scope: I, kind: 'observance', themes: ['education'] },
  { m: 9, d: 16, name: 'International Day for the Preservation of the Ozone Layer', scope: W, kind: 'observance', themes: ['environment', 'health'] },
  { m: 9, d: 17, name: 'World Hindi Day (India)',      scope: I, kind: 'observance', themes: ['education'], note: 'India — celebrates Hindi and world-language translators.' },
  { m: 9, d: 19, name: 'International Day for Older Persons', scope: W, kind: 'observance', themes: ['social-inclusion', 'health'] },
  { m: 9, d: 21, name: 'International Day of Peace',   scope: W, kind: 'observance', themes: ['rights', 'community'] },
  { m: 9, d: 22, name: 'World Car Free Day',           scope: W, kind: 'observance', themes: ['environment', 'health', 'disability'] },
  { m: 9, d: 23, name: 'International Day of Sign Languages', scope: W, kind: 'observance', themes: ['disability', 'education'], note: 'Direct fit for inclusive communication and sign-language training.' },
  { m: 9, d: 27, name: 'World Social Service Day',     scope: W, kind: 'observance', themes: ['social-inclusion', 'rights'] },
  { m: 9, d: 28, name: 'World Rabies Day',             scope: W, kind: 'observance', themes: ['health'] },
  { m: 9, d: 30, name: 'International Translation Day',scope: W, kind: 'observance', themes: ['education'] },

  /* October */
  { m: 10, d: 1, name: 'International Day of the Elderly', scope: W, kind: 'observance', themes: ['social-inclusion', 'health'] },
  { m: 10, d: 1, name: "National Senior Citizens' Day (India)", scope: I, kind: 'observance', themes: ['social-inclusion', 'health', 'rights'] },
  { m: 10, d: 2, name: 'Gandhi Jayanti (India)',        scope: I, kind: 'national',   themes: ['rights', 'community'] },
  { m: 10, d: 2, name: 'International Day of Non-Violence', scope: W, kind: 'observance', themes: ['rights', 'community'], note: 'UN-designated, observed on Gandhi Jayanti.' },
  { m: 10, d: 5, name: "World Teachers' Day",          scope: W, kind: 'observance', themes: ['education'] },
  { m: 10, d: 10, name: 'World Mental Health Day',      scope: W, kind: 'observance', themes: ['health', 'rights'], note: 'Largest global mental-health campaign date.' },
  { m: 10, d: 11, name: 'International Day of the Girl Child', scope: W, kind: 'observance', themes: ['women-children', 'education', 'rights'] },
  { m: 10, d: 16, name: 'World Food Day',              scope: W, kind: 'observance', themes: ['nutrition', 'livelihoods'] },
  { m: 10, d: 17, name: 'International Day for the Elimination of Poverty', scope: W, kind: 'observance', themes: ['livelihoods', 'social-inclusion'] },
  { m: 10, d: 20, name: 'World Osteoporosis Day',       scope: W, kind: 'observance', themes: ['health'] },
  { m: 10, d: 24, name: 'United Nations Day',           scope: W, kind: 'observance', themes: ['rights', 'education'] },
  { m: 10, d: 27, name: 'World Day for Audiovisual Heritage', scope: W, kind: 'observance', themes: ['education', 'sports-culture'] },
  { m: 10, d: 31, name: 'Rashtriya Ekta Diwas / Sardar Patel Jayanti (India)', scope: I, kind: 'national', themes: ['rights', 'community'] },

  /* November */
  { m: 11, d: 14, name: "Children's Day (India)",      scope: I, kind: 'observance', themes: ['children', 'education', 'rights'], note: 'India — celebrates child rights and welfare.' },
  { m: 11, d: 14, name: 'World Diabetes Day',           scope: W, kind: 'observance', themes: ['health', 'nutrition'], note: 'Designed for screening camps and diet counselling.' },
  { m: 11, d: 19, name: 'World Toilet Day',             scope: W, kind: 'observance', themes: ['health', 'environment'], note: 'Strong fit for accessible-toilet and sanitation work.' },
  { m: 11, d: 20, name: "Universal Children's Day (UN)", scope: W, kind: 'observance', themes: ['children', 'education', 'rights'] },
  { m: 11, d: 25, name: 'International Day for the Elimination of Violence against Women', scope: W, kind: 'observance', themes: ['women-children', 'rights'], note: 'UN-designated; runs the global #OrangeTheWorld campaign.' },

  /* December */
  { m: 12, d: 1, name: 'World AIDS Day',               scope: W, kind: 'observance', themes: ['health', 'rights'] },
  { m: 12, d: 2, name: 'International Day for the Abolition of Slavery', scope: W, kind: 'observance', themes: ['rights', 'social-inclusion'] },
  { m: 12, d: 3, name: 'International Day of Persons with Disabilities', scope: W, kind: 'observance', themes: ['disability', 'rights'], note: 'UN-designated; core date for accessibility and inclusion drives.' },
  { m: 12, d: 5, name: 'International Volunteer Day (UN)', scope: W, kind: 'observance', themes: ['community', 'social-inclusion'], note: 'Fits volunteer recognition drives.' },
  { m: 12, d: 5, name: 'World Soil Day',               scope: W, kind: 'observance', themes: ['environment', 'livelihoods'], note: 'Fits soil-health and farming livelihoods.' },
  { m: 12, d: 9, name: 'International Day against Corruption', scope: W, kind: 'observance', themes: ['rights'] },
  { m: 12, d: 10, name: 'Human Rights Day (UN)',       scope: W, kind: 'observance', themes: ['rights', 'social-inclusion'] },
  { m: 12, d: 12, name: 'Universal Health Coverage Day (UN)', scope: W, kind: 'observance', themes: ['health', 'rights'] },
  { m: 12, d: 18, name: 'International Migrant Day (UN)', scope: W, kind: 'observance', themes: ['social-inclusion', 'livelihoods'] },
  { m: 12, d: 20, name: 'International Human Solidarity Day (UN)', scope: W, kind: 'observance', themes: ['social-inclusion', 'rights'] },
  { m: 12, d: 25, name: 'Christmas',                    scope: W, kind: 'religious', themes: ['community', 'sports-culture'], note: 'Widely used for gift-distribution and celebration programmes.' },
];

/* ── Per-year rows for date-varying festivals ──────────────────────────────── */
// Only years listed here produce entries; any other year simply omits the
// lunar festivals rather than guessing a date. `precision: 'lunar'` is surfaced
// in the UI as "confirm the gazette date".
const BY_YEAR = {
  2024: [
    { date: '2024-01-15', name: 'Makar Sankranti / Pongal',      scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2024-01-22', name: 'Vasant Panchami',                scope: I, kind: 'festival', themes: ['education', 'sports-culture'], precision: 'lunar' },
    { date: '2024-02-14', name: 'Mahashivratri',                  scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2024-03-08', name: 'Holi (Dhulandi)',                scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2024-03-25', name: 'Ugadi / Gudi Padwa / Chaitra Navratri', scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2024-04-09', name: 'Hanuman Jayanti',                scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2024-04-11', name: 'Id-ul-Fitr (Ramzan Eid)',        scope: I, kind: 'religious', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2024-04-17', name: 'Ram Navami',                     scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2024-05-01', name: 'Akshaya Tritiya',                scope: I, kind: 'festival', themes: ['livelihoods', 'community'], precision: 'lunar' },
    { date: '2024-05-23', name: 'Buddha Purnima',                 scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2024-06-17', name: 'Id-ul-Adha (Bakrid)',            scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2024-08-15', name: 'Krishna Janmashtami',            scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2024-08-26', name: 'Onam',                           scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2024-09-07', name: 'Anant Chaturdashi',               scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2024-10-03', name: 'Sharad Navratri begins',         scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2024-10-12', name: 'Durga Ashtami',                  scope: I, kind: 'religious', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2024-10-12', name: 'Diwali (Deepavali)',             scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2024-10-15', name: 'Dhanteras',                      scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2024-11-07', name: 'Chhath Puja',                    scope: I, kind: 'religious', themes: ['community', 'health'], precision: 'lunar' },
    { date: '2024-11-15', name: 'Guru Nanak Jayanti',             scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
  ],
  2025: [
    { date: '2025-01-14', name: 'Makar Sankranti / Pongal',      scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2025-02-02', name: 'Vasant Panchami',                scope: I, kind: 'festival', themes: ['education', 'sports-culture'], precision: 'lunar' },
    { date: '2025-02-26', name: 'Mahashivratri',                  scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2025-03-14', name: 'Holi (Dhulandi)',                scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2025-03-30', name: 'Ugadi / Gudi Padwa / Chaitra Navratri', scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2025-03-31', name: 'Id-ul-Fitr (Ramzan Eid)',        scope: I, kind: 'religious', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2025-04-06', name: 'Ram Navami',                     scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-04-10', name: 'Mahavir Jayanti',                scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-04-30', name: 'Akshaya Tritiya',                scope: I, kind: 'festival', themes: ['livelihoods', 'community'], precision: 'lunar' },
    { date: '2025-05-12', name: 'Buddha Purnima',                 scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-06-07', name: 'Id-ul-Adha (Bakrid)',            scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2025-08-09', name: 'Raksha Bandhan',                 scope: I, kind: 'festival', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2025-08-16', name: 'Krishna Janmashtami',            scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-08-26', name: 'Onam',                           scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2025-08-27', name: 'Ganesh Chaturthi',               scope: I, kind: 'festival', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-09-06', name: 'Anant Chaturdashi',               scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2025-10-11', name: 'Sharad Navratri begins',         scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2025-10-19', name: 'Durga Ashtami',                  scope: I, kind: 'religious', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2025-10-20', name: 'Diwali (Deepavali)',             scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2025-10-20', name: 'Vijayadashami (Dussehra)',       scope: I, kind: 'festival', themes: ['community'], precision: 'lunar' },
    { date: '2025-11-05', name: 'Guru Nanak Jayanti',             scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2025-11-08', name: 'Chhath Puja',                    scope: I, kind: 'religious', themes: ['community', 'health'], precision: 'lunar' },
  ],
  2026: [
    { date: '2026-01-14', name: 'Makar Sankranti / Pongal',      scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2026-01-23', name: 'Vasant Panchami',                scope: I, kind: 'festival', themes: ['education', 'sports-culture'], precision: 'lunar' },
    { date: '2026-02-15', name: 'Mahashivratri',                  scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2026-03-04', name: 'Holi (Dhulandi)',                scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2026-03-19', name: 'Ugadi / Gudi Padwa / Chaitra Navratri', scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2026-03-20', name: 'Id-ul-Fitr (Ramzan Eid)',        scope: I, kind: 'religious', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2026-03-27', name: 'Ram Navami',                     scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2026-04-25', name: 'Mahavir Jayanti',                scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2026-04-14', name: 'Akshaya Tritiya',                scope: I, kind: 'festival', themes: ['livelihoods', 'community'], precision: 'lunar' },
    { date: '2026-05-01', name: 'Buddha Purnima',                 scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2026-05-27', name: 'Id-ul-Adha (Bakrid)',            scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2026-08-26', name: 'Onam',                           scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2026-08-28', name: 'Raksha Bandhan',                 scope: I, kind: 'festival', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2026-09-04', name: 'Krishna Janmashtami',            scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2026-09-14', name: 'Ganesh Chaturthi',               scope: I, kind: 'festival', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2026-09-24', name: 'Anant Chaturdashi',               scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2026-10-11', name: 'Sharad Navratri begins',         scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2026-10-19', name: 'Durga Ashtami',                  scope: I, kind: 'religious', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2026-10-19', name: 'Diwali (Deepavali)',             scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2026-10-20', name: 'Vijayadashami (Dussehra)',       scope: I, kind: 'festival', themes: ['community'], precision: 'lunar' },
    { date: '2026-11-15', name: 'Chhath Puja',                    scope: I, kind: 'religious', themes: ['community', 'health'], precision: 'lunar' },
    { date: '2026-11-24', name: 'Guru Nanak Jayanti',             scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
  ],
  2027: [
    { date: '2027-01-15', name: 'Makar Sankranti / Pongal',      scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2027-02-11', name: 'Vasant Panchami',                scope: I, kind: 'festival', themes: ['education', 'sports-culture'], precision: 'lunar' },
    { date: '2027-03-06', name: 'Mahashivratri',                  scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2027-03-09', name: 'Id-ul-Fitr (Ramzan Eid)',        scope: I, kind: 'religious', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2027-03-22', name: 'Holi (Dhulandi)',                scope: I, kind: 'festival', themes: ['community', 'sports-culture'], precision: 'lunar' },
    { date: '2027-04-07', name: 'Ugadi / Gudi Padwa / Chaitra Navratri', scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2027-04-13', name: 'Mahavir Jayanti',                scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2027-05-16', name: 'Id-ul-Adha (Bakrid)',            scope: I, kind: 'religious', themes: ['community'], precision: 'lunar' },
    { date: '2027-05-20', name: 'Buddha Purnima',                 scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2027-08-15', name: 'Onam',                           scope: I, kind: 'festival', themes: ['community', 'nutrition'] },
    { date: '2027-08-17', name: 'Raksha Bandhan',                 scope: I, kind: 'festival', themes: ['community', 'women-children'], precision: 'lunar' },
    { date: '2027-08-25', name: 'Krishna Janmashtami',            scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2027-10-04', name: 'Ganesh Chaturthi',               scope: I, kind: 'festival', themes: ['community', 'education'], precision: 'lunar' },
    { date: '2027-10-09', name: 'Diwali (Deepavali)',             scope: I, kind: 'festival', themes: ['community', 'nutrition'], precision: 'lunar' },
    { date: '2027-10-09', name: 'Vijayadashami (Dussehra)',       scope: I, kind: 'festival', themes: ['community'], precision: 'lunar' },
    { date: '2027-11-06', name: 'Chhath Puja',                    scope: I, kind: 'religious', themes: ['community', 'health'], precision: 'lunar' },
    { date: '2027-11-14', name: 'Guru Nanak Jayanti',             scope: I, kind: 'religious', themes: ['community', 'education'], precision: 'lunar' },
  ],
};

/* ── Date helpers (UTC-anchored so the server timezone can never shift a day) ─ */
const pad2 = (n) => String(n).padStart(2, '0');
const ymd = (y, m, d) => `${y}-${pad2(m)}-${pad2(d)}`;

function daysInMonth(y, monthIdx0) { return new Date(Date.UTC(y, monthIdx0 + 1, 0)).getUTCDate(); }

/** 'YYYY-MM-DD' of the nth (1-based) weekday (0=Sun) in a month. */
function nthWeekday(y, monthIdx0, weekday, n) {
  const first = new Date(Date.UTC(y, monthIdx0, 1)).getUTCDay();
  let day = 1 + ((weekday - first + 7) % 7) + (n - 1) * 7;
  while (day > daysInMonth(y, monthIdx0)) day -= 7;
  return ymd(y, monthIdx0 + 1, day);
}

/** Anonymous Gregorian computus → 'YYYY-MM-DD'. */
function easterSunday(y) {
  const a = y % 19;
  const b = Math.floor(y / 100);
  const c = y % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return ymd(y, month, day);
}

const shiftYmd = (s, days) => {
  const t = new Date(`${s}T00:00:00Z`).getTime() + days * 86400000;
  return new Date(t).toISOString().slice(0, 10);
};

/* ── Weekday-rule observances (computed, therefore always correct) ─────────── */
// resolve(year) → 'YYYY-MM-DD'. Built on the Date object so there is no
// hand-written date arithmetic to get wrong.
const WEEKDAY_RULES = [
  { name: "Mother's Day",       scope: W, kind: 'observance', themes: ['women-children', 'social-inclusion', 'health'],
    resolve: (y) => nthWeekday(y, 4, 0, 2) },   // 2nd Sunday of May
  { name: 'World Kindness Day', scope: W, kind: 'observance', themes: ['community', 'education', 'rights'],
    resolve: (y) => nthWeekday(y, 10, 2, 2) },  // 2nd Tuesday of November
  { name: 'Good Friday',        scope: W, kind: 'religious', themes: ['community'],
    resolve: (y) => shiftYmd(easterSunday(y), -2) },
];

/* ── Public API ───────────────────────────────────────────────────────────── */

export const SUPPORTED_LUNAR_YEARS = Object.keys(BY_YEAR).map(Number).sort();

/** Years that have curated data (fixed rules work for every year). */
export const availableYears = () => {
  const now = new Date().getUTCFullYear();
  const years = new Set([...SUPPORTED_LUNAR_YEARS]);
  for (let y = now - 3; y <= now + 3; y++) years.add(y);
  return [...years].sort((a, b) => a - b);
};

const norm = (row) => {
  // `m`/`d` are authoring scaffolding for the fixed rules — never ship them.
  const { m, d, ...rest } = row;
  return {
    scope: 'worldwide',
    kind: 'observance',
    themes: [],
    precision: 'fixed',
    source: 'curated',
    note: null,
    ...rest,
    themes: Array.isArray(rest.themes) ? rest.themes : [],
  };
};

/**
 * Every curated observance/festival whose date falls inside [startYmd, endYmd).
 * Purely deterministic — the input range is the only thing that varies.
 *
 * @param {string} startYmd  inclusive, 'YYYY-MM-DD'
 * @param {string} endYmd    exclusive, 'YYYY-MM-DD'
 * @param {object} opts      { scope: 'all' | 'worldwide' | 'india' }
 */
export function getObservancesInRange(startYmd, endYmd, opts = {}) {
  const scope = ['all', 'worldwide', 'india'].includes(opts.scope) ? opts.scope : 'all';
  const inScope = (s) => scope === 'all' || s === scope;
  const out = [];

  const startDate = new Date(`${startYmd}T00:00:00Z`);
  const endDate = new Date(`${endYmd}T00:00:00Z`);
  if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime()) || endDate <= startDate) return out;

  const startYear = startDate.getUTCFullYear();
  const endYear = endDate.getUTCFullYear();

  for (let y = startYear; y <= endYear; y++) {
    // 1. Fixed month/day rules.
    for (const row of FIXED) {
      if (!inScope(row.scope)) continue;
      const d = ymd(y, row.m, row.d);
      if (d >= startYmd && d < endYmd) out.push(norm({ ...row, date: d }));
    }
    // 2. Per-year festival rows (omitted entirely when the year has no data).
    for (const row of BY_YEAR[y] || []) {
      if (!inScope(row.scope)) continue;
      if (row.date >= startYmd && row.date < endYmd) out.push(norm({ ...row }));
    }
    // 3. Computed weekday rules.
    for (const rule of WEEKDAY_RULES) {
      if (!inScope(rule.scope)) continue;
      const s = rule.resolve(y);
      if (s >= startYmd && s < endYmd) out.push(norm({ ...rule, date: s }));
    }
  }

  out.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.name.localeCompare(b.name)));
  return out;
}

/** The observances on one specific calendar day (used by the suggestion flow). */
export function getObservancesOnDate(dateYmd) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(dateYmd || ''))) return [];
  const d = new Date(`${dateYmd}T00:00:00Z`);
  const next = new Date(d.getTime() + 86400000);
  return getObservancesInRange(dateYmd, next.toISOString().slice(0, 10), { scope: 'all' });
}

/** Union of every theme slug used by the dataset — handy for prompt grounding. */
export function allThemes() {
  const s = new Set();
  for (const r of FIXED) for (const t of r.themes || []) s.add(t);
  for (const rows of Object.values(BY_YEAR)) for (const r of rows) for (const t of r.themes || []) s.add(t);
  for (const r of WEEKDAY_RULES) for (const t of r.themes || []) s.add(t);
  return [...s].sort();
}

/**
 * Merge operator-managed `holidays` rows over the curated list. A DB row with the
 * same date + name replaces the curated entry (so corrections win) and anything
 * else is appended as an extra entry. Never throws — a DB failure degrades to
 * the curated list only.
 */
export function mergeCustomObservances(list, holidayRows) {
  const out = list.map((o) => ({ ...o }));
  const key = (o) => `${o.date}::${String(o.name).trim().toLowerCase()}`;
  const seen = new Set(out.map(key));
  for (const h of holidayRows || []) {
    const date = String(h.date || '').slice(0, 10);
    const name = String(h.name || '').trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !name) continue;
    const k = `${date}::${name.toLowerCase()}`;
    // A curated row with the same name on the same day IS the same occasion. An
    // operator correcting or re-scoping it in the holidays table must win, so
    // replace the curated copy instead of dropping the new row on the floor.
    const at = out.findIndex((o) => key(o) === k);
    if (at !== -1) {
      out[at] = {
        ...out[at],
        date,
        name,
        scope: h.ngo_id ? 'india' : 'worldwide',
        kind: out[at].kind,
        themes: out[at].themes,
        precision: out[at].precision,
        note: h.description || h.note || out[at].note,
        source: 'db',
      };
      continue;
    }
    if (seen.has(k)) continue;
    seen.add(k);
    out.push({
      date,
      name,
      scope: h.ngo_id ? 'india' : 'worldwide',
      kind: 'observance',
      themes: [],
      precision: 'fixed',
      source: 'db',
      note: h.description || h.note || null,
    });
  }
  out.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.name.localeCompare(b.name)));
  return out;
}
