export const SIM_CARD_SEED = [
  { id: 1, mobile_id: 'Android 1', device_model: null, imei: null, team: "Neha Kharwar", signature: null, issue_date: '2026-02-04', expiry_date: '2026-03-04', status: 'Active', replacement_count: 0 },
  { id: 2, mobile_id: 'Android 2', device_model: null, imei: null, team: "Neha Kharwar", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 3, mobile_id: 'Android 3', device_model: null, imei: null, team: "Neha Kharwar", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 4, mobile_id: 'Android 4', device_model: null, imei: null, team: "Neha Kharwar", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 5, mobile_id: 'Android 5', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 6, mobile_id: 'Android 6', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 7, mobile_id: 'Android 7', device_model: null, imei: null, team: "Hiral Waghela", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 8, mobile_id: 'Android 8', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 9, mobile_id: 'Android 9', device_model: null, imei: null, team: "Hiral Waghela", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 10, mobile_id: 'Android 10', device_model: null, imei: null, team: "Hiral Waghela", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 11, mobile_id: 'Android 11', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 12, mobile_id: 'Android 12', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 13, mobile_id: 'Android 13', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 14, mobile_id: 'Android 14', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 15, mobile_id: 'Android 15', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 16, mobile_id: 'Android 16', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 17, mobile_id: 'Android 17', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 18, mobile_id: 'Android 18', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 19, mobile_id: 'Android 19', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 20, mobile_id: 'Android 20', device_model: null, imei: null, team: "Kshitija Jadhav", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 21, mobile_id: 'Android 21', device_model: null, imei: null, team: "Deepa Tiwari", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 22, mobile_id: 'Android 22', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 23, mobile_id: 'Android 23', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 24, mobile_id: 'Android 24', device_model: null, imei: null, team: "Deepak Karkera", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 25, mobile_id: 'Android 25', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 26, mobile_id: 'Android 26', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 27, mobile_id: 'Android 27', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 28, mobile_id: 'Android 28', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 29, mobile_id: 'Android 29', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 30, mobile_id: 'Android 30', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 31, mobile_id: 'Android 31', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 32, mobile_id: 'Android 32', device_model: null, imei: null, team: "Deepa Tiwari", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 33, mobile_id: 'Android 33', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 34, mobile_id: 'Android 34', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 35, mobile_id: 'Android 35', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 36, mobile_id: 'Android 36', device_model: null, imei: null, team: "Deepak Karkera", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 37, mobile_id: 'Android 37', device_model: null, imei: null, team: "Kshitija Jadhav", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 38, mobile_id: 'Android 38', device_model: null, imei: null, team: "Deepa Tiwari", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 39, mobile_id: 'Android 39', device_model: null, imei: null, team: "Deepa Tiwari", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 40, mobile_id: 'Android 40', device_model: null, imei: null, team: "Deepak Karkera", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 41, mobile_id: 'Android 41', device_model: null, imei: null, team: "Deepak Karkera", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 42, mobile_id: 'Android 42', device_model: null, imei: null, team: "Sakshi Singh", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 43, mobile_id: 'Android 43', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 44, mobile_id: 'Android 44', device_model: null, imei: null, team: "Kshitija Jadhav", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 45, mobile_id: 'Android 45', device_model: null, imei: null, team: "Deepa Gupta", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 46, mobile_id: 'Android 46', device_model: null, imei: null, team: "Anjana Vyas", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 47, mobile_id: 'Android 47', device_model: null, imei: null, team: "HR", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 48, mobile_id: 'Android 48', device_model: null, imei: null, team: "AFLF Admin Prachi", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
  { id: 49, mobile_id: 'Android 49', device_model: null, imei: null, team: "BSCT Admin Vaishali", signature: null, issue_date: null, expiry_date: null, status: 'Active', replacement_count: 0 },
];
