-- 085: Per-user accounts access codes (no schema change).
-- Access codes are now stored per accounts user inside the existing `settings`
-- table under the key `accounts_access_code_<userId>` (formerly a single shared
-- key `accounts_access_code`). The old shared key is no longer verified.
--
-- No DDL is required: this is a documentation of the key layout only. The legacy
-- shared key may be cleaned up after confirming all users have set a code of their own.
--
-- Optional cleanup (run manually once users have migrated):
--   DELETE FROM settings WHERE key = 'accounts_access_code';
