-- 087: Seed SIM Card / Mobile ID records (49 Mobile IDs) from the provided data export.

INSERT INTO sim_cards
  (mobile_id, device_model, imei, team, signature, issue_date, expiry_date, status, replacement_count)
VALUES
  ('Android 1', NULL, NULL, 'Neha Kharwar', NULL, '2026-02-04', '2026-03-04', 'Active', 0),
('Android 2', NULL, NULL, 'Neha Kharwar', NULL, NULL, NULL, 'Active', 0),
('Android 3', NULL, NULL, 'Neha Kharwar', NULL, NULL, NULL, 'Active', 0),
('Android 4', NULL, NULL, 'Neha Kharwar', NULL, NULL, NULL, 'Active', 0),
('Android 5', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 6', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 7', NULL, NULL, 'Hiral Waghela', NULL, NULL, NULL, 'Active', 0),
('Android 8', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 9', NULL, NULL, 'Hiral Waghela', NULL, NULL, NULL, 'Active', 0),
('Android 10', NULL, NULL, 'Hiral Waghela', NULL, NULL, NULL, 'Active', 0),
('Android 11', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 12', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 13', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 14', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 15', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 16', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 17', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 18', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 19', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 20', NULL, NULL, 'Kshitija Jadhav', NULL, NULL, NULL, 'Active', 0),
('Android 21', NULL, NULL, 'Deepa Tiwari', NULL, NULL, NULL, 'Active', 0),
('Android 22', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 23', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 24', NULL, NULL, 'Deepak Karkera', NULL, NULL, NULL, 'Active', 0),
('Android 25', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 26', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 27', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 28', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 29', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 30', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 31', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 32', NULL, NULL, 'Deepa Tiwari', NULL, NULL, NULL, 'Active', 0),
('Android 33', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 34', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 35', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 36', NULL, NULL, 'Deepak Karkera', NULL, NULL, NULL, 'Active', 0),
('Android 37', NULL, NULL, 'Kshitija Jadhav', NULL, NULL, NULL, 'Active', 0),
('Android 38', NULL, NULL, 'Deepa Tiwari', NULL, NULL, NULL, 'Active', 0),
('Android 39', NULL, NULL, 'Deepa Tiwari', NULL, NULL, NULL, 'Active', 0),
('Android 40', NULL, NULL, 'Deepak Karkera', NULL, NULL, NULL, 'Active', 0),
('Android 41', NULL, NULL, 'Deepak Karkera', NULL, NULL, NULL, 'Active', 0),
('Android 42', NULL, NULL, 'Sakshi Singh', NULL, NULL, NULL, 'Active', 0),
('Android 43', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 44', NULL, NULL, 'Kshitija Jadhav', NULL, NULL, NULL, 'Active', 0),
('Android 45', NULL, NULL, 'Deepa Gupta', NULL, NULL, NULL, 'Active', 0),
('Android 46', NULL, NULL, 'Anjana Vyas', NULL, NULL, NULL, 'Active', 0),
('Android 47', NULL, NULL, 'HR', NULL, NULL, NULL, 'Active', 0),
('Android 48', NULL, NULL, 'AFLF Admin Prachi', NULL, NULL, NULL, 'Active', 0),
('Android 49', NULL, NULL, 'BSCT Admin Vaishali', NULL, NULL, NULL, 'Active', 0);
