-- 168: remove the hidden_until parking mechanism from fro_assignments.
--
-- hidden_until was a "park this lead until date X" column. Every disposition
-- wrote it (dnd and donation_collected → first of next month; scheduled →
-- the scheduled time; retryable not-connected → next IST day; everything else
-- → first of next month) and getMyDonors then filtered those rows out of the
-- working list until the date passed.
--
-- It was redundant with the status/rollover machinery already in place, and it
-- actively fought the "show me all my data" rule: a worked or disposed lead was
-- dropped from My Leads entirely, which is what produced the "my allotment says
-- N but I can only see M" reports. It was also invisible — a lead disappeared
-- with no badge explaining why.
--
-- Parking is dropped, not replaced. After this migration the ONLY automatic
-- holds left in getMyDonors are an explicit DND mark (donor_dnd) and a donation
-- completed in the current period. Every other lead stays visible and is surfaced
-- through the status filters and the row badge instead. The controlled queue
-- (workableFiltered) still never re-serves a lead already worked today or already
-- terminal, so auto-advance behaviour is unchanged.
--
-- Callbacks promised to a donor are unaffected: next_follow_up and
-- fro_scheduled_contacts were never parking mechanisms, and since this change the
-- monthly rollover no longer clears next_follow_up — a promised callback keeps its
-- date across the month boundary.
--
-- All values are NULL (see hidden_until_backup), so this drop is not a data loss.

-- Dependencies: none expected (no view/trigger/function reads the column; it was
-- only written and selected by application code). Verified before running.
alter table public.fro_assignments
  drop column if exists hidden_until;